services:
  - type: web
    name: trilock-api
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: PLATFORM_ENCRYPTION_KEY
        value: a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2
      - key: TOTP_SECRET
        generateValue: true
      - key: UPLOAD_DIR
        value: ./uploads
      - key: CORS_ORIGIN
        value: https://tri-lock.vercel.app
      - key: OMNIDIM_API_KEY
        value: WCsM7V0A4Us3UMfrHHK1B3O0ndThHD-58VoaHh2QqQM
      - key: OMNIDIM_AGENT_ID
        value: "205814"
